routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pagoda','FrontendController@index');

Route::group(['prefix' => 'admin' , 'middleware' => 'auth'], function () {
	Route::get('/','DashboardController@index');
	Route::resource('/founder','FounderController');
	Route::resource('/pagoda','PagodaController');
});

app/Pagoda.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;


class Pagoda extends Model
{
	use SoftDeletes;
	use Sluggable;

    protected $fillable = ['name','lat','lng','founder_id','built_in','description','image_id','slug'];

    /**
    * Return the sluggable configuration array for this model.
    *
    * @return array
    */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }

    public function image()
    {
    	return $this->belongsTo(PagodaImage::class,'image_id','id');
    }
}

app/Http/Controllers/PagodaController.php
<?php

namespace App\Http\Controllers;

use App\Pagoda;
use App\Founder;
use Illuminate\Http\Request;
use App\Http\Requests\PagodaEditRequest;
use App\Http\Requests\PagodaCreateRequest;

use App\Traits\ManagesImages;
use App\PagodaImage;

class PagodaController extends Controller
{
    use ManagesImages;

    // public function __construct()
    // {
    //     $this->setImageDefaultsFromConfig('pagodaImage');
    // }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $pagodas = Pagoda::orderBy('name')->get();
        return view('admin.pagoda.index',compact('pagodas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $founders = Founder::pluck('name','id');
        return view('admin.pagoda.create',compact('founders'));        
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(PagodaCreateRequest $request)
    {   
        $pagodaImage = $this::storeImage($request);
        
        $request->request->add([ 'image_id' => $pagodaImage->id ]);
        $pagoda = Pagoda::create($request->all());

        return redirect()->route('pagoda.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Pagoda  $pagoda
     * @return \Illuminate\Http\Response
     */
    public function show(Pagoda $pagoda)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Pagoda  $pagoda
     * @return \Illuminate\Http\Response
     */
    public function edit(Pagoda $pagoda)
    {
        $founders = Founder::pluck('name','id');
        $image = $pagoda->image()->first();
        $image = 'thumb-'. $image->image_name . '.' . $image->image_extension;
        return view('admin.pagoda.edit',compact('pagoda','founders','image'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Pagoda  $pagoda
     * @return \Illuminate\Http\Response
     */
    public function update(PagodaEditRequest $request,Pagoda $pagoda)
    {
        if ($request->hasFile('image')) {
             $this::updateImage($request,$pagoda);
        }

        $pagoda->update($request->all());

        return redirect()->route('pagoda.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Pagoda  $pagoda
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pagoda $pagoda)
    {
        $pagoda->delete();

        return redirect()->back();
    }

    private function generateRandomString($length = 5) {
        $characters = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
        $charactersLength = strlen($characters);
        $randomString = '';
        for ($i = 0; $i < $length; $i++) {
            $randomString .= $characters[rand(0, $charactersLength - 1)];
        }
        return $randomString;
    }

    private function storeImage($request)
    {
        $this->setImageDefaultsFromConfig('pagodaImage');
        
        $pagodaImage = new PagodaImage([
            'image_name'        =>  $this::generateRandomString().'-'. mt_rand(10,10000),
            'image_extension'   => $request->file('image')->getClientOriginalExtension(),
            ]);
        
        $pagodaImage->save();

        // get instance of file
        $file = $this->getUploadedFile();

        // pass in the file and the model
        $this->saveImageFiles($file, $pagodaImage);

        return $pagodaImage;
    }


    private function updateImage($request, $pagoda)
    {
        $this->setImageDefaultsFromConfig('pagodaImage');

        if ($pagoda->image()->first()) {
            $pagodaImage = PagodaImage::find($pagoda->image_id);

            // if file, we have additional requirements before saving
            if ($this->newFileIsUploaded()) {
                $this->deleteExistingImages($pagodaImage);
                $this->setNewFileExtension($request, $pagodaImage);
            }

            $pagodaImage->save();

            // check for file, if new file, overwrite existing file
            if ($this->newFileIsUploaded()){                
                $file = $this->getUploadedFile();                
                $this->saveImageFiles($file, $pagodaImage);
            }
        }
        else
        {
            $this::storeImage($request);
        }
    }

     /**
     * @param EditImageRequest $request
     * @param $marketingImage
     */

    private function setNewFileExtension($request,$pagodaImage)
    { 
        $pagodaImage->image_extension = $request->file('image')->getClientOriginalExtension();
    }
}

resources/views/admin/pagoda/create.blade.php
@extends('layouts.dashboard')

@section('heading')
Pagoda Create
@endsection

@section('createButton')
<a href="{{ route('pagoda.index') }}" class="btn btn-success">Back</a>
@endsection

@section('content')

<div class="box box-default">
	<div class="box-header with-border">

		{!! Form::open(array('route' => 'pagoda.store','method' => 'post','enctype'=>"multipart/form-data")) !!}
		
		<div class="box-body">
		
		@include('admin.pagoda.form')
		
		</div>

		<div class="box-footer">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
		
		{!! Form::close() !!}
	</div>
</div>

@endsection

resources/views/admin/pagoda/edit.blade.php
@extends('layouts.dashboard')

@section('heading')
Pagoda Edit
@endsection

@section('createButton')
<a href="{{ route('pagoda.index') }}" class="btn btn-primary">Back</a>
@endsection


@section('content')

<div class="box box-default">
	<div class="box-header with-border">

		{!! Form::model($pagoda,['route' => ['pagoda.update',$pagoda->id],'method' => 'put','enctype'=>"multipart/form-data"]) !!}

		<div class="box-body">			
			@include('admin.pagoda.form')

			<div class="form-group col-md-6">
				{{ Form::label(null, 'Current Image') }} </br>
				<img src="{{ asset('/images/pagodas/thumbnails/'.$image) }}" alt="">			
			</div>

		</div>

		<div class="box-footer">
			<button type="submit" class="btn btn-primary">Update</button>
		</div>
		
		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/admin/pagoda/form.blade.php
			<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
				{{ Form::label('name', 'Name') }}
				{{ Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Enter Name' ]) }}
				@if ($errors->has('name'))
				<span class="help-block">
					{{ $errors->first('name') }}
				</span>
				@endif				
			</div>
			<div class="row">
				<div class="form-group {{ $errors->has('lat') ? ' has-error' : '' }} col-md-6">
					{{ Form::label('lat', 'Lattitute') }}
					{{ Form::text('lat',null, ['class' => 'form-control', 'placeholder' => 'Enter Lattitute' ]) }}
					@if ($errors->has('lat'))
					<span class="help-block">
						{{ $errors->first('lat') }}
					</span>
					@endif				
				</div>

				<div class="form-group {{ $errors->has('lng') ? ' has-error' : '' }} col-md-6">
					{{ Form::label('lng', 'Longitude') }}
					{{ Form::text('lng',null, ['class' => 'form-control', 'placeholder' => 'Enter Longitude' ]) }}
					@if ($errors->has('lng'))
					<span class="help-block">
						{{ $errors->first('lng') }}
					</span>
					@endif				
				</div>
			</div>
			<div class="row">
				<div class="form-group {{ $errors->has('founder_id') ? ' has-error' : '' }} col-md-6">
					{{ Form::label('founder_id', 'Founder') }}					
					{{ Form::select('founder_id', $founders, null, ['class'=>'form-control','placeholder' => 'Choose Founder Name...']) }}
					@if ($errors->has('founder_id'))
					<span class="help-block">
						{{ $errors->first('founder_id') }}
					</span>
					@endif				
				</div>

				<div class="form-group {{ $errors->has('built_in') ? ' has-error' : '' }} col-md-6">
					{{ Form::label('built_in', 'Built In') }}
					{{ Form::text('built_in',null, ['class' => 'form-control', 'placeholder' => 'Enter Built In Year' ]) }}
					@if ($errors->has('built_in'))
					<span class="help-block">
						{{ $errors->first('built_in') }}
					</span>
					@endif				
				</div>
			</div>

			<div class="form-group {{ $errors->has('description') ? ' has-error' : '' }}">
				{{ Form::label('description', 'Description') }}
				{{ Form::textarea('description',null, ['class' => 'form-control', 'placeholder' => 'Enter Description' ]) }}
				@if ($errors->has('description'))
				<span class="help-block">
					{{ $errors->first('description') }}
				</span>
				@endif				
			</div>

			<div class="form-group {{ $errors->has('image') ? ' has-error' : '' }} col-md-6">
				{{ Form::label('image', 'Image') }}
				{{ Form::file('image',null,['class'=>'form-control']) }}
				@if ($errors->has('image'))
				<span class="help-block">
					{{ $errors->first('image') }}
				</span>
				@endif				
			</div>

resources/views/admin/pagoda/index.blade.php
@extends('layouts.dashboard')

@section('heading')
Pagoda
@endsection

@section('createButton')
<a href="{{ route('pagoda.create') }}" class="btn btn-primary">Create</a>
@endsection

@section('content')
<div class="box">
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="col-md-9">Name</th>
					<th class="col-md-3"></th>					
				</tr>
			</thead>
			<tbody>
				@foreach ($pagodas as $pagoda)
				<tr>
					<td>{{$pagoda->name}}</td>	
					<td>
						<div class="row">
							<div class="col-md-4">
								<a class="btn btn-primary" href="{{ route('pagoda.edit',$pagoda->id) }}">Edit</a>
							</div>
							<div class="col-md-8">
								<form action="{{ route('pagoda.destroy', $pagoda->id) }}" method="post">
									{{ csrf_field() }}
									{{ method_field('delete') }}
									<button class="btn btn-danger">Delete</button>
								</form>
							</div>
						</div>
					</td>				
				</tr>
				@endforeach                
			</tbody>
			<tfoot>
				<tr>
					<th>Name</th>					
				</tr>
			</tfoot>
		</table>
	</div>
</div>
@endsection

@section('script')
<!-- DataTables -->
<script src="{{ asset('/vendor/js/jquery.dataTables.min.js') }} "></script>
<script src="{{ asset('/vendor/js/dataTables.bootstrap.min.js') }}"></script>
<script>
	$(function () {
		$('#example1').DataTable({
			'paging'      : true,
			'lengthChange': false,
			'searching'   : true,
			'ordering'    : true,
			'info'        : true,
			'autoWidth'   : false
		})
	})
</script>
@endsection