routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/pagoda','FrontendController@index');

Route::group(['prefix' => 'admin' , 'middleware' => 'auth'], function () {
	Route::get('/','DashboardController@index');
	Route::resource('/founder','FounderController');
	Route::resource('/pagoda','PagodaController');
});

app/Founder.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Cviebrock\EloquentSluggable\Sluggable;

class Founder extends Model
{
	use SoftDeletes;
	use Sluggable;
	
    protected $fillable = ['name','slug'];

     /**
     * Return the sluggable configuration array for this model.
     *
     * @return array
     */
    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'name'
            ]
        ];
    }
}

app/Http/Controllers/FounderController.php
<?php

namespace App\Http\Controllers;

use App\Founder;
use Illuminate\Http\Request;

class FounderController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $founders = Founder::orderBy('name')->get();
        return view('admin.founder.index',compact('founders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.founder.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,['name'=>'required']);
        Founder::create($request->all());
        return redirect()->route('founder.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Founder  $founder
     * @return \Illuminate\Http\Response
     */
    public function show(Founder $founder)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Founder  $founder
     * @return \Illuminate\Http\Response
     */
    public function edit(Founder $founder)
    {
        return view('admin.founder.edit',compact('founder'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Founder  $founder
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Founder $founder)
    {
        $this->validate($request,['name'=>'required']);
        $founder->update($request->all());
        return redirect()->route('founder.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Founder  $founder
     * @return \Illuminate\Http\Response
     */
    public function destroy(Founder $founder)
    {
        $founder->delete();
        return redirect()->back();
    }
}

resources/views/admin/founder/create.blade.php
@extends('layouts.dashboard')

@section('heading')
Founder
@endsection

@section('content')

<div class="box box-default">
	<div class="box-header with-border">

		{!! Form::open(array('route' => 'founder.store','method' => 'post')) !!}

		<div class="box-body">
			<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
				{{ Form::label('name', 'Name') }}
				{{ Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Enter Name' ]) }}
				@if ($errors->has('name'))
				<span class="help-block">
					{{ $errors->first('name') }}
				</span>
				@endif				
			</div>
		</div>
		
		<div class="box-footer">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
		
		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/admin/founder/edit.blade.php
@extends('layouts.dashboard')

@section('content')

<div class="box box-default">
	<div class="box-header with-border">

		{!! Form::model($founder,array('route' => ['founder.update',$founder->id],'method' => 'put')) !!}

		<div class="box-body">
			<div class="form-group {{ $errors->has('name') ? ' has-error' : '' }}">
				{{ Form::label('name', 'Name') }}
				{{ Form::text('name',null, ['class' => 'form-control', 'placeholder' => 'Enter Name' ]) }}
				@if ($errors->has('name'))
				<span class="help-block">
					{{ $errors->first('name') }}
				</span>
				@endif				
			</div>
		</div>

		<div class="box-footer">
			<button type="submit" class="btn btn-primary">Submit</button>
		</div>
		
		{!! Form::close() !!}
	</div>
</div>
@endsection

resources/views/admin/founder/index.blade.php
@extends('layouts.dashboard')

@section('heading')
Founder
@endsection

@section('createButton')
<a class="btn btn-primary" href="{{ route('founder.create') }}">Create</a>
@endsection

@section('content')
<div class="box">
	<div class="box-body">
		<table id="example1" class="table table-bordered table-striped">
			<thead>
				<tr>
					<th class="col-md-9">Name</th>
					<th class="col-md-3"></th>					
				</tr>
			</thead>
			<tbody>
				@foreach ($founders as $founder)
				{{-- expr --}}

				<tr>
					<td>{{$founder->name}}</td>	
					<td>
						<div class="row">
							<div class="col-md-4">
								<a class="btn btn-primary" href="{{ route('founder.edit',$founder->id) }}">Edit</a>
							</div>
							<div class="col-md-8">
								<form action="{{ route('founder.destroy', $founder->id) }}" method="post">
									{{ csrf_field() }}
									{{ method_field('delete') }}
									<button class="btn btn-danger">Delete</button>
								</form>
							</div>
						</div>
					</td>				
				</tr>
				@endforeach                
			</tbody>
			<tfoot>
				<tr>
					<th>Name</th>					
				</tr>
			</tfoot>
		</table>
	</div>
</div>
@endsection

@section('script')
<!-- DataTables -->
<script src="../../bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
<script src="../../bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
<script>
	$(function () {
		$('#example2').DataTable({
			'paging'      : true,
			'lengthChange': false,
			'searching'   : false,
			'ordering'    : true,
			'info'        : true,
			'autoWidth'   : false
		})
	})
</script>
@endsection